run:
	chmod +777 soln/.build/build.sh
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -e --timeout 5
all:
	chmod +777 soln/.build/build.sh
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases --timeout 5
verbose:
	chmod +777 soln/.build/build.sh
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -e -v --timeout 5
all-verbose:
	chmod +777 soln/.build/build.sh
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -v --timeout 5
